#!/usr/bin/bash
CG="gcc -g -std=c17 -fmax-errors=5"

echo "Compiling..."
if [[ $# == 2 ]]
then
    if [[ -e $2.c ]]
    then
        if [[ $1 == "-m32" ]]
        then
            echo $2
            $CG -m32 $2.c -o $2 && ./$2
        else if [[ $1 == "-lp" ]]
        then
            $CG $2.c -lpthread -o $2 && ./$2
        else
            echo "invalid argument at position 1: $1"
            echo "usage: gc <filename> <args>"
            echo "  where <args> is '-m64' or '-lp'"
        fi
    fi
    else
        echo "sorry, $2.c does not exist"
    fi
else if [[ -e $1.c ]]
then 
    $CG $1.c -o $1 && ./$1

else
    echo "sorry, $1.c does not exist"
    echo "usage: "
    echo "  gc <filename> <args>"
    echo "  where <args> is '-m32' or '-lp'"
fi
fi
