#!/bin/bash

virtualenv -p python3 env

if [[ ! -e .env ]]; then
cat >.env <<ENV_EOF
source env/bin/activate
ENV_EOF
fi

source .env
pip install pytest

echo "------------------------------"
echo "'env' created. You can now:"
echo "source .env"
