#!/bin/bash

tomov1="public class $1 {"
tomov2="    public $1() {"
tomov3="    }"
tomov4=""
tomov5="    public static void main(string[] args) {"
tomov6="    }"
tomov7="}"


mkdir $1
mkdir ./$1/bin
mkdir ./$1/src
cd ./$1/src
touch $1.java
echo "${tomov1}" >> $1.java
echo "${tomov2}" >> $1.java
echo "${tomov3}" >> $1.java
echo "${tomov4}" >> $1.java
echo "${tomov5}" >> $1.java
echo "${tomov6}" >> $1.java
echo "${tomov7}" >> $1.java
